spring:
  config:
    activate:
      on-profile: proxy

  kafka:
    # kafka server
    bootstrap-servers: 192.168.45.135:9092
    consumer:
      group-id: lucas
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3