server:
  port: 8080

spring:
  application:
    name: boot-kafka

  profiles:
    active: proxy

  config:
    import:
      - classpath:/config/application-local.yml
      - classpath:/config/application-proxy.yml

  main:
    allow-circular-references: true


# Swagger Login Setting (Token)
#springdoc:
#  show-login-endpoint: true