spring:
  config:
    activate:
      on-profile: local


  # mariaDB Config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot_kafka?useSSL=false
    username: root
    password: 1234


  # JPA Config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  sql:
    init:
      mode: never



  # kafka Config
  kafka:
    # kafka server
    bootstrap-servers: localhost:9092
    consumer:
      # bootstrap-servers: Other ServerIP:9092
      # consumer Group Target Id
      group-id: lucas
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # bootstrap-servers: Other ServerIP:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer